[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Claus Thomasen <claus.thomasen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
langgraph = "^0.2.53"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
